name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 10.8.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint admin
        run: pnpm admin:lint

      - name: Lint web
        run: pnpm web:lint

      - name: Build admin
        run: pnpm admin:build

      - name: Build web
        run: pnpm web:build
